insert into USERS (ID, USERNAME, PASSWORD, STATUS) values (1, 'ocano@company.xyz', 'pass123', 'ACTIVE');
insert into USERS (ID, USERNAME, PASSWORD, STATUS) values (2, 'ocano2@company.xyz', 'pass123', 'ACTIVE');
insert into USERS (ID, USERNAME, PASSWORD, STATUS) values (3, 'ocano3@company.xyz', 'pass123', 'INACTIVE');

insert into OPERATIONS(ID, TYPE, COST) values (1, 'ADDITION', 1.25);
insert into OPERATIONS(ID, TYPE, COST) values (2, 'SUBTRACTION', 1.25);
insert into OPERATIONS(ID, TYPE, COST) values (3, 'MULTIPLICATION', 1.25);
insert into OPERATIONS(ID, TYPE, COST) values (4, 'DIVISION', 1.25);
insert into OPERATIONS(ID, TYPE, COST) values (5, 'SQUARE_ROOT', 1.25);
insert into OPERATIONS(ID, TYPE, COST) values (6, 'RANDOM_STRING', 1.25);

insert into RECORDS(ID, OPERATION_ID, USER_ID, AMOUNT, USER_BALANCE, OPERATION_RESPONSE, CREATED_DATE) values (1, '8c913748-5cb6-4021-8127-4c64e7ac1e87', 1, 1.25, 50.99, 'SUCCESS', CURRENT_TIMESTAMP());
insert into RECORDS(ID, OPERATION_ID, USER_ID, AMOUNT, USER_BALANCE, OPERATION_RESPONSE, CREATED_DATE) values (2, '9664b782-7641-483b-afad-38d15919eb23', 2, 1.25, 50.99, 'SUCCESS', CURRENT_TIMESTAMP());
insert into RECORDS(ID, OPERATION_ID, USER_ID, AMOUNT, USER_BALANCE, OPERATION_RESPONSE, CREATED_DATE) values (3, 'f60fd49a-d93b-434a-836d-88492168afa7', 3, 1.25, 50.99, 'FAILED', CURRENT_TIMESTAMP());