insert into USERS (USERNAME, PASSWORD, ENABLED) values ('ocano@company.xyz', '$2a$12$uBrHpJB27j/aEgIPiIWleOTBMm/OWMLEgA8JYTgykybB7ZGOiYasu', 1);
insert into USERS (USERNAME, PASSWORD, ENABLED) values ('ocano2@company.xyz', '$2a$12$uBrHpJB27j/aEgIPiIWleOTBMm/OWMLEgA8JYTgykybB7ZGOiYasu', 1);
insert into USERS (USERNAME, PASSWORD, ENABLED) values ('ocano3@company.xyz', '$2a$12$uBrHpJB27j/aEgIPiIWleOTBMm/OWMLEgA8JYTgykybB7ZGOiYasu', 0);
INSERT INTO USER_ROLES (USERNAME, ROLENAME) VALUES ('ocano@company.xyz', 'ROLE_ADMIN');
INSERT INTO USER_ROLES (USERNAME, ROLENAME) VALUES ('ocano2@company.xyz', 'ROLE_USER');
INSERT INTO USER_ROLES (USERNAME, ROLENAME) VALUES ('ocano3@company.xyz', 'ROLE_USER');


insert into OPERATIONS(ID, TYPE, COST) values (1, 'ADDITION', 1.25);
insert into OPERATIONS(ID, TYPE, COST) values (2, 'SUBTRACTION', 1.25);
insert into OPERATIONS(ID, TYPE, COST) values (3, 'MULTIPLICATION', 1.25);
insert into OPERATIONS(ID, TYPE, COST) values (4, 'DIVISION', 1.25);
insert into OPERATIONS(ID, TYPE, COST) values (5, 'SQUARE_ROOT', 1.25);
insert into OPERATIONS(ID, TYPE, COST) values (6, 'RANDOM_STRING', 1.25);

insert into RECORDS(ID, OPERATION_ID, USER_ID, AMOUNT, USER_BALANCE, OPERATION_RESPONSE, CREATED_DATE) values (1,'8c913748-5cb6-4021-8127-4c64e7ac1e87', 'ocano@company.xyz', 1.25, 50.99, 'SUCCESS', CURRENT_TIMESTAMP());
insert into RECORDS(ID, OPERATION_ID, USER_ID, AMOUNT, USER_BALANCE, OPERATION_RESPONSE, CREATED_DATE) values (2, '8c913748-5cb6-4021-8127-4c64e7ac1e87', 'ocano@company.xyz', 1.25, 49.99, 'SUCCESS', CURRENT_TIMESTAMP());
insert into RECORDS(ID, OPERATION_ID, USER_ID, AMOUNT, USER_BALANCE, OPERATION_RESPONSE, CREATED_DATE) values (3, '9664b782-7641-483b-afad-38d15919eb23', 'ocano2@company.xyz', 1.25, 50.99, 'SUCCESS', CURRENT_TIMESTAMP());
insert into RECORDS(ID, OPERATION_ID, USER_ID, AMOUNT, USER_BALANCE, OPERATION_RESPONSE, CREATED_DATE) values (4,  'f60fd49a-d93b-434a-836d-88492168afa7', 'ocano3@company.xyz', 1.25, 50.99, 'FAILED', CURRENT_TIMESTAMP());